### PR TITLE
Control Box Communication Protocol

### PR DESCRIPTION
**Pull request by MarkGhebrial**
I wrote up a spec for the control box protocol. Please comment if I made any mistakes.

The idea for this repository is that the specifications here are canonical. If a device or firmware complies with these specs, then it should work in our systems.

### CODE REVIEW

**Comment by zanderdo** [comment]
Good except for the line about no acknowledgement.  Current acknowledgement returns an uint8 with the 5 rightmost bits representing the states of each servo and the igniter.  1 is open/activated, 0 is closed.  Order from left to right is NOS2, NOS1, N2, ETOH, IGNITER.  Acknowledgement is sent after each received command, including check state which just sends back the ack.

**Comment by MarkGhebrial** [comment]
@zanderdo, just added the acknowledgement specification. Please merge if everything looks ok.

**Comment by zanderdo** [comment]
@MarkGhebrial Almost, just shift the bits 3 to the right and you're good.  So NOS2 would be on bit 5.  Sorry my explanation was a little confusing.  Once that's done it's perfect!

**Comment by MarkGhebrial** [comment]
Fixed! I'll merge tomorrow if there are no other mistakes.

**Pull request merged**
